server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: localhost:9092
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: user_app
    schema-action: CREATE_IF_NOT_EXISTS
    connection:
      connect-timeout: 5s
      init-query-timeout: 5s
    local-datacenter: datacenter1
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: 24675e854c23f198b53695053c65ce96089e1e3f77ea43104f1a30e21406fa9c
